#!/usr/bin/perl -w
# Copyright (C) 2014 Miquel Sabaté Solà
# This file is licensed under the MIT license.
# See the LICENSE file.

# This script allows us to connect with psql properly for the given environment.
#
# The environments that we can use have to be specified in a JSON file. This
# JSON file has to be specified in the "$json" configurable value (by default
# is "db/database.json"). This JSON file has to specify the environments
# available and a set of values. Each environment has to specify the following
# values:
#
#   * dbname: the name of the database.
#   * host: the host to be used.
#   * user: the user that is accessing the database.
#   * password: the password for the user@host.
#
# More values can be specified, but they will be ignored by this script. You
# can find an example of this in the examples/database.json file.
#
# You can call this script with the following optional arguments:
#
#   -e name
#       This argument can be used to specify the environment that we want to
#       connect to. If this argument has not been passed, it will take the
#       value of the "$default" configurable value ("development" by default).
#
#   -m, --migrate
#       This argument can be used to migrate a set of .sql files into the
#       database. The path to these files can be set with the "$migrate"
#       configurable value (by default it is "db/migrate").
#
#   b, --backup
#       spit to the STDOUT a backup of the database.
#
# Therefore, this command has the following usage:
#
#   $ db [-e name] [[-m | --migrate] | [-b | --backup]]
#

use strict;
use File::Basename;
use Cwd 'abs_path', 'getcwd';


##
# Config values. Ideally you should only modify these values to adapt this
# script to your project.
#
# NOTE: path values should *not* start and/or end with a slash.


# The base path that this script will use. By default it picks the current
# working directory.
my $base = abs_path(getcwd);

# The relative path to the json file (including the name of the json file
# itself).
my $json = 'db/database.json';

# The default environment. This is the environment to be used when no
# environment has been given through the '-e' option.
my $default = 'development';

# The relative path with migration files. Migration files are plain .sql files
# that will be used with the '-m' option.
my $migrate = 'db/migrate';


##
# And here starts the program itself.


# Show the usage string and exit.
sub usage {
    print "Usage: db [-e name] [[-m | --migrate] | [-b | --backup]]\n";
    print "  -e  Specify an environment.\n";
    print "  -m  Migrate all the files from the db/migrate directory.\n";
    print "  -b  Backup the proper DB.\n";
    exit(1);
}

# Check that a given value has been defined in the given hash.
sub check {
    my ($ary, $value) = @_;
    if (!defined($ary->{$value})) {
        print "ERROR: you haven't defined the '$value' value.\n";
        exit(1);
    }
}

# Parsing options.
my %opts = ('e', $default, 'm', 0, 'b', 0);
for (my $it = 0; $it < @ARGV; $it++) {
    if ($ARGV[$it] eq '-e') {
        usage() if (!$ARGV[$it + 1]);
        $opts{e} = $ARGV[$it + 1];
        $it++;
    } elsif ($ARGV[$it] eq '-m' || $ARGV[$it] eq '--migrate') {
        $opts{m} = 1;
    } elsif ($ARGV[$it] eq '-b' || $ARGV[$it] eq '--backup') {
        $opts{b} = 1;
    } else {
        if ($ARGV[$it] ne '-h' && $ARGV[$it] ne '--help') {
            print "Unknown option `$ARGV[$it]'\n\n";
        }
        usage();
    }
}

# Let's fetch the configuration of the environment.
my $config = "$base/$json";
if (!-f $config) {
    print "ERROR: the $config file does not exist!\n";
    exit(1)
}

open(FILE, $config);
my $file = '';
while (<FILE>) {
    my $line = $_;
    chomp($line);
    $file .= " $line";
}
close(FILE);

# Fetch the values.
$file =~ m/"$opts{e}":\s?({(.*?)})/;
my $contents = $1;
if (!defined($contents)) {
    print "The `$opts{e}' environment does not exist.\n";
    exit(1);
}

# Setup the command.
my %ary = ();
$ary{$1} = $2 while ($contents =~ /"(\w+)":\s?"([\w\-]*)"/g);
foreach (qw{dbname user host password}) {
    check(\%ary, $_);
}

my $opts = "-d $ary{'dbname'} -U $ary{'user'} -h $ary{'host'}";
my $cmd = "PGPASSWORD=$ary{'password'} psql $opts";

# Now execute the command properly.
if ($opts{m}) {
    opendir(DIR, "$base/$migrate/") or die $!;
    while (my $file = readdir(DIR)) {
        next if ($file =~ m/^\./);
        next if ($file !~ m/\.sql$/);

        system("$cmd < $base/$migrate/$file\n");
    }
    closedir(DIR);
} elsif ($opts{b}) {
    my $opts = "-d $ary{'dbname'} -U $ary{'user'}";
    system("PGPASSWORD=$ary{'password'} pg_dump $opts");
} else {
    system("$cmd");
}
