#!/bin/bash
# Copyright (C) 2013-2015 Miquel Sabaté Solà
# This file is licensed under the MIT license.
# See the LICENSE file.

set -e

if !(which go &> /dev/null); then
    echo "ERROR: you don't have go installed!"
    exit 1
fi

# Install/update dependencies
dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.."
cd $dir
godep restore

# PostgreSQL
base="todo"
if [ ! -f "$dir/db/database.json" ]; then
    read -p 'PostgreSQL User: ' user
    echo -n 'PostgreSQL Password: '
    read -s password
    echo
    cat <<DB > "$dir/db/database.json"
{
    "development": {
        "user": "$user",
        "dbname": "$base-dev",
        "password": "$password",
        "host": "localhost",
        "sslmode": "disable"
    },
    "production": {
        "user": "$user",
        "dbname": "$base",
        "password": "$password",
        "host": "localhost",
        "sslmode": "disable"
    },
    "test": {
        "user": "$user",
        "dbname": "$base-test",
        "password": "$password",
        "host": "localhost",
        "sslmode": "disable"
    }
}
DB
fi
