#!/bin/bash
# Copyright (C) 2014-2017 Miquel Sabaté Solà
#
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cssdir="$dir/../public/stylesheets"

# On deploy, execute once and exit.
if [ "$TODO_DEPLOY" = "1" ]; then
    set -e
    sass --update "$cssdir"
    exit 0
fi

# Launch a background job that deal with Sass.

# Get pidfile.
todo="/tmp/todo"
mkdir -p $todo
pidfile="$todo/assets.pid"
touch $pidfile

# Kill off old processes
while read pid; do
  kill $pid > /dev/null 2>&1;
done < $pidfile

# Truncate the PID file
> $pidfile

# If the user just wanted to stop all old processes, then exit here.
if [[ $1 == "stop" ]]; then
  exit 1
fi

# SASS
csslog="$todo/sass.log"
sass --watch "$cssdir" > $csslog 2>&1 &
echo $! >> $pidfile
