#!/bin/bash
# Copyright (C) 2014 Miquel Sabaté Solà <mikisabate@gmail.com>
# This file is licensed under the MIT license.
# See the LICENSE file.


# Run the test suite. For some reason we cannot call: go test -v ./..., because
# then the test suite has some random crashes :/


dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )/.."
for d in lib $dir app models; do
    cd $d
    go test
done

