#!/bin/bash
# Copyright (C) 2014 Miquel Sabaté Solà <mikisabate@gmail.com>
# This file is licensed under the MIT license.
# See the LICENSE file.


# Check which command to use.
cmd="start"
if [ "$1" != "" ]; then
    cmd="$1"
fi

# Archlinux-specific stuff.
ps -e | grep systemd > /dev/null
if [ $? -eq 0 ]; then
    sudo systemctl $cmd postgresql
fi

# Call the assets script.
dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
source $dir/sass $cmd
